#3
human-osaka-game-2019/Thirteen pull request #14
Opened 2019-08-29 03:19 UTC by hiroto1130

## 元issue

#3 

## 内容
画像読み込み関数

2019-08-29 03:25 UTC, taishi-matsumura commented
@hiroto1130 
* pull requestのtitle
他のteamのpgが見たときに、pull requestの内容わかると思いますか？
* description
reviewerが見たときに、修正内容わかると思いますか？

『No』なのであれば修正して下さい。

2019-08-29 03:35 UTC, hiroto1130 commented
修正してみました、どうでしょうか？

2019-08-29 03:38 UTC, taishi-matsumura commented
> 修正してみました、どうでしょうか？

いいと思います 👍

2019-08-29 04:19 UTC, taishi-matsumura requested changes
たまたま見ちゃったので指摘しておきます。

2019-08-29 04:19 UTC, taishi-matsumura commented on Thirteen/Texture.cpp
> +void LoadTexture(const char* file_name, int SelectScene, int  SelectTexture)
なぜglobalな関数？

2019-08-29 04:19 UTC, taishi-matsumura commented on Thirteen/Texture.h
> +class MapChipData
ファイル名とクラス名が別な理由は？

2019-08-29 04:19 UTC, taishi-matsumura commented on Thirteen/Texture.h
> +#define TEXTURE_H
ファイル末尾のコメントも修正すべきですね。

2019-08-29 04:19 UTC, taishi-matsumura commented on Thirteen/Texture.cpp
> +static LPDIRECT3DDEVICE9 pDevice;
無名のnamespaceに入れるとかしましょう。

参考：https://ttsuki.github.io/styleguide/cppguide.ja.html#Unnamed_Namespaces_and_Static_Variables

2019-08-29 04:40 UTC, hiroto1130 commented on Thirteen/Texture.cpp
> +static LPDIRECT3DDEVICE9 pDevice;
今回は使用しない方向で行くそうなので、勉強だけしておきます

2019-08-29 04:54 UTC, hiroto1130 commented on Thirteen/Texture.cpp
> +static LPDIRECT3DDEVICE9 pDevice;
一通り修正しました

2019-08-29 06:53 UTC, taishi-matsumura requested changes
カプセル化しないの？

2019-08-29 06:53 UTC, taishi-matsumura commented on Thirteen/MapchipData.h
> +	float MapChipHeight;
publicなメンバ変数？

2019-08-29 06:55 UTC, taishi-matsumura commented on Thirteen/MapchipData.h
> +#define MAPCHIPDATA_H
全部大文字or小文字の場合は単語の区切りがわからなくなるのでsnakeにすることが多いです。

2019-08-29 07:56 UTC, taishi-matsumura requested changes

2019-08-29 07:56 UTC, taishi-matsumura commented on Thirteen/MapchipData.h
> +#define MapChipData_H
これはsnakeじゃないですね

2019-08-29 07:59 UTC, taishi-matsumura commented on Thirteen/Texture.h
> +	void InputTextureSize(int Height, int Width)
単純にメンバ変数を設定する関数では無いですが、それでも `InputXXXX()` よりは `SetXXX()` の方がマシだと思います。

2019-08-29 08:02 UTC, taishi-matsumura commented
本筋とは関係無いですが、『commitをした』≒『codeを修正した』なので、commitメッセージの一行目に「code修正」と書くのは無意味ですね。
後からcommit logを見たときに、どのcommitで何をしたのかがわかるメッセージになるよう心掛けましょう。

2019-08-29 08:06 UTC, taishi-matsumura commented
例えば直近のcommitであれば、
```
InputXXX()をSetXXX()に変更

- InputMapChipSize を SetMapChipSize に変更
- InputTextureSize を SetTextureSize に変更
```
とかじゃないですか？

「titleとして用いられる1行目と、詳細として用いられる3行目以後が同じ概念レベルなのは変だな」という感覚を早く身に付けましょう。
日本語の文章で概念レベルを合わせられない人は関数も概念レベルがバラバラのものを混在させがちで、極めて読みづらいコードを書きます。迷惑です。

2019-08-30 16:15 UTC, taishi-matsumura approved these changes

2019-08-30 16:17 UTC, taishi-matsumura commented
松村指摘ぶんはapproveしておきました。

@hiroto1130 
commit整理してから、@OkamotoKazumaにmergeしてもらって下さい。

2019-09-01 07:59 UTC, merged